language: node_js
node_js:
  - "node"
install:
  - yarn
script:
  - yarn lint
  - bower install
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - yarn build && now build --public --name react-weather-app --token $NOW_TOKEN && now alias --token $NOW_TOKEN --force
