language: node_js
node_js:
  - "node"
before_install:
  - npm install -g bower  
install:
  - yarn
  - bower install
script:
  - yarn lint
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script:
    - yarn build && now build --public --name react-weather-app --token $NOW_TOKEN && now alias --token $NOW_TOKEN --force
